### ISSUE TITLE
Contar Pedidos por Clientes

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/lanche_bot#10]

**Comment by Pauloparakleto** [comment]
O cliente tem nome e um número de telefone(este único). Ele não tem senha. Sua solicitação pelo celular é sua autenticação.

**Comment by Pauloparakleto** [comment]
Essa demanda depende de #7, #9 Perguntar para o sênior se é possível avançar nesta isolada das outras.
