### ISSUE TITLE
Cadastrar Menus

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/lanche_bot#3]
Menu principal:

1. Nome do Lanche;
2. Descrição;
3. Preço.

Menu de sucos:

1. Nome da bebida;
2. Tamanho do copo (default 300ml);
3. Preço.

Menu de refrigerantes:
1. Nome da marca;
2. Sabor;
3. Tipo de embalagem (enum: "ks", "1L",  "1,5L", "2L")
4. Preço.

**Comment by diegoshakan** [comment]
@Pauloparakleto quais seriam os campos desta feature?

**Comment by Pauloparakleto** [comment]
> @Pauloparakleto quais seriam os campos desta feature?

Acredito que os Menus que não são o principal talvez sejam movidos para outras issues. Acredito que esta issue pode ser encerrada com o Menu principal. Vamos alinhar com o senior amanhã, @diegoshakan.
