### ISSUE TITLE
Cadastrar Promoções

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/lanche_bot#6]

**Comment by Pauloparakleto** [comment]
Promoção:

1. tem um combo (inicialmente);
2. tem vários clientes habilitados de acordo com os critérios da promoção ao contar quantidade de pedidos. Esta quantidade de pedidos não é absoluta, deve ser da regra da promoção.
2. lanche e quantidade;
3. suco e quantidade.
