### ISSUE TITLE
Cadastrar Lanchonetes

### ISSUE THREAD

**Issue by marcodotcastro** [desenvolvendo-me/lanche_bot#8]
Lanchonete
1. nome;
2. endereço;
3. horário de abertura;
4. horário de fechar.

Os relacionamentos:
1. tem muitos clientes;
2. tem um menu;
3. tem várias promoções;
4. tem vários combos.

**Comment by Pauloparakleto** [comment]
Lanchonete

1. tem muitos clientes;
2. tem um menu;
3. tem várias promoções;
4. tem vários combos.

**Comment by Pauloparakleto** [comment]
Faltam campos: horários de abertura e fechamento.
